project:
  type: website
  output-dir: docs

website:
  title: "Example of Title"
  sidebar:
    style: "docked"
    search: false
    contents:
      - section: "PBHLTH"
        contents:
          - lectures/Lecture_1.qmd
          - lectures/Lecture_2.qmd
      - section: "Layout"
        contents:
          - layout-jupyter.qmd

format:
  html:
    theme: docked
    css: styles.css
    toc: true

editor: visual